# force trigger schedule
name: Line Notify

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node checkAndNotify.js
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}

      - name: Debug time
        run: |
          echo "RUNNING SCHEDULE"
          date
